language: node_js
node_js:
  - 13

env:
  - SERVICENAME=udagram-api-feed
  - SERVICENAME=udagram-api-user
  - SERVICENAME=udagram-reverseproxy
  - SERVICENAME=udagram-frontend

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t $SERVICENAME ./$SERVICENAME
  - docker tag $SERVICENAME mikeattara/$SERVICENAME:v1

# Tasks to perform after the process is successful.
# Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push mikeattara/$SERVICENAME:v1
