apiVersion: v1
kind: Service
metadata:
  name: backend-user
  labels:
    service: backend-user
spec:
  ports:
    - name: "8080"
      port: 8081
      targetPort: 8081
  selector:
    service: backend-user
