apiVersion: v1
kind: Service
metadata:
  labels:
    service: backend-feed
  name: backend-feed
spec:
  ports:
    - name: "8080"
      port: 8082
      targetPort: 8082
  selector:
    service: backend-feed
